---
apiVersion: v1
kind: Namespace
metadata:
  name: my-app
---
apiVersion: syn.tools/v1
kind: RedisInstance
metadata:
  name: redis1
  namespace: my-app
spec:
  parameters:
    storageSize: 10Gi
    resources:
      limits:
        memory: 0.2Gi
