= Getting Started

This page describes how to order a new managed Redis instance and consume it in an application.

== Prerequisites

* `kubectl`

== Steps

. Create a new namespace `my-redis`.
+
[source,bash]
----
kubectl create namespace my-redis
----

. Create the following new `RedisInstance` resource in a new `instance.yaml` file.
+
[source,yaml]
----
apiVersion: syn.tools/v1
kind: RedisInstance
metadata:
  name: my-instance <1>
  namespace: my-redis
spec:
  parameters:
    resources:
      storageSize: 1Gi
    updatePolicy:
      version: latest
----
<1> Name of the instance.
    Be sure to not make it too long.

. Apply the resource.
+
[source,bash]
----
kubectl apply -f instance.yaml
----

. Wait until the instance is ready.
+
[source,bash]
----
kubectl -n my-redis wait --for condition=Ready RedisInstance.syn.tools/my-instance --timeout 180s
----

. Verify that there's a new `Secret` generated in the `my-redis` namespace.
+
[source,bash]
----
kubectl -n my-redis get secret my-instance-credentials
----

. Configure the application to use the credentials provided.
  For the purpose of this guide we will just run a Redis ping but it should demonstrate how to configure the Redis parameters for an app.
+
.app.yaml
[source,yaml]
----
apiVersion: batch/v1
kind: Job
metadata:
  name: service-connection-verify
  namespace: my-redis
spec:
  backoffLimit: 0
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: redis-client
          image: docker.io/bitnami/redis:6.0.12-debian-10-r3
          command:
            - sh
            - -c
          args:
            - redis-cli -h "${REDIS_HOST}" -p ${REDIS_PORT} ping
          env:
            - name: REDIS_HOST
              valueFrom:
                secretKeyRef:
                  name: my-instance-credentials
                  key: endpoint
            - name: REDIS_PORT
              valueFrom:
                secretKeyRef:
                  name: my-instance-credentials
                  key: port
            - name: REDISCLI_AUTH
              valueFrom:
                secretKeyRef:
                  name: my-instance-credentials
                  key: password
----

. Verify that the application can talk to Redis.
+
[source,bash]
----
kubectl wait -n my-redis --for condition=Complete job/service-connection-verify
----

== Further Reading

* xref:references/api-spec.adoc[API Specification]
