resources:
  - namespace.yaml
  - secret.yaml
  - service.yaml
  - rbac.yaml
  - deployment.yaml
  - ingress.yaml

namespace: service-broker
commonLabels:
  app.kubernetes.io/instance: redis
  app.kubernetes.io/name: service-broker
