---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    name: service-broker
  name: service-broker
  namespace: service-broker
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    name: service-broker
  name: service-broker
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: crossplane-edit
subjects:
  - kind: ServiceAccount
    name: service-broker
    namespace: service-broker
