name: Build

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  crossplane:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Run build
        run: make build
