name: Build

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

env:
  KIND_CMD: kind # kind is pre-installed in GitHub runners

jobs:
  crossplane:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Run build
        run: make build
