name: Build

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  crossplane:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Determine Go version from go.mod
        run: echo "GO_VERSION=$(grep "go 1." go.mod | cut -d " " -f 2)" >> $GITHUB_ENV

      - uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Run build
        run: make build
